### ISSUE TITLE
Question about predict and visualization

### ISSUE THREAD

**Issue by eagle-liang** [francescotonini/object-aware-gaze-target-detection#10]
Dear authors:
Thank you for a  great work!  But I ran into some mistakes that bothered me for 3 weeks in eval.py. Can you help me ?( My intention was to visualize the predicted images and get the labels in txt format. )

Looking forward to your reply.

line 99: predictions = trainer.predict(model=model, dataloaders=datamodule.test_dataloader(), ckpt_path=cfg.ckpt_path)
            
                                                                              
Traceback (most recent call last):
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\eval.py", line 108, in main
    evaluate(cfg)
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\utils\utils.py", line 42, in wrap
    raise ex
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\utils\utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\eval.py", line 99, in evaluate
    predictions = trainer.predict(model=model, dataloaders=datamodule.test_dataloader(), ckpt_path=cfg.ckpt_path)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 850, in predict
    return call._call_and_handle_interrupt(
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 897, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1061, in _run
    results = self._run_stage()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1139, in _run_stage
    return self._run_predict()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1193, in _run_predict
    return self.predict_loop.run()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\loops\dataloader\prediction_loop.py", line 97, in advance
    dataloader_iter = enumerate(dataloader)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\dataloader.py", line 437, in __iter__
    self._iterator = self._get_iterator()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in __init__
    self._reset(loader, first_iter=True)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\dataloader.py", line 1118, in _reset
    self._try_put_index()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\dataloader.py", line 1352, in _try_put_index
    index = self._next_index()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\dataloader.py", line 624, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\overrides\distributed.py", line 132, in __iter__
    for batch in self._sampler:
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\torch\utils\data\sampler.py", line 76, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Predicting: 0it [00:01, ?it/s]

Process finished with exit code 1

**Comment by francescotonini** [comment]
Hi! If you are interested in visualizing the predicted images you can have a look [here](https://github.com/francescotonini/object-aware-gaze-target-detection/blob/main/src/models/gotd_module.py#L176), where I process the network outputs to build nice qualitatives. I believe with minimal changes you can replace the log to wandb with a `image.save` on your local disk. The same goes for saving predictions to .txt.

**Comment by eagle-liang** [comment]
haha,it is so hard to me.Because I didn't major in computer science.

**Comment by eagle-liang** [comment]
Anyway,there is another error. Normally, the prediction process only takes images as input, but in line 154 of gazefollow_objects_datamodule.py:
def test_dataloader(self):
return self.val_dataloader()
This leads to the prediction process also requiring annotation information. Do you know how to modify it?
I sincerely hope that you can improve the prediction code, which will enable your research to make a greater contribution and promote its application to other fields.
