### ISSUE TITLE
Checkpoint Unavailable

### ISSUE THREAD

**Issue by eagle-liang** [francescotonini/object-aware-gaze-target-detection#13]
Traceback (most recent call last):
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\test.py", line 473, in main
    evaluate(cfg)
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\utils\utils.py", line 42, in wrap
    raise ex
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\utils\utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "D:\Pycharmprojects\object-aware-gaze-target-detection-main\src\test.py", line 129, in evaluate
    predictions = trainer.predict(model=model, dataloaders=datamodule.test_dataloader(), ckpt_path=cfg.ckpt_path)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 850, in predict
    return call._call_and_handle_interrupt(
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 897, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1005, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 961, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\trainer\connectors\checkpoint_connector.py", line 271, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "D:\ruanjian\anaconda\envs\object-aware-gaze-target-detection\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
KeyError: 'state_dict'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by francescotonini** [comment]
Hi! I updated the README with instructions on how to evaluate on the public checkpoints.
