### ISSUE TITLE
Dataset Correlation

### ISSUE THREAD

**Issue by Ki-Zhang** [francescotonini/object-aware-gaze-target-detection#2]
Hello, the currently downloaded [Gazefollow dataset](http://gazefollow.csail.mit.edu/download.html) does not contain "bbox_x_min", "bbox_y_min", "bbox_x_max", "bbox_y_max". And the latest [videoattentiontarget dataset](https://www.dropbox.com/s/8ep3y1hd74wdjy5/videoattentiontarget.zip?dl=0) cant't run the script below:
```bash
# GazeFollow
python scripts/gazefollow_get_aux_faces.py --dataset_path /path/to/gazefollow --subset train
python scripts/gazefollow_get_aux_faces.py --dataset_path /path/to/gazefollow --subset test
python scripts/gazefollow_get_objects.py --dataset_path /path/to/gazefollow --subset train
python scripts/gazefollow_get_objects.py --dataset_path /path/to/gazefollow --subset test

# VideoAttentionTarget
python scripts/videoattentiontarget_get_aux_faces.py --dataset_path /path/to/videoattentiontarget --subset train
python scripts/videoattentiontarget_get_aux_faces.py --dataset_path /path/to/videoattentiontarget --subset test
python scripts/videoattentiontarget_get_objects.py --dataset_path /path/to/videoattentiontarget --subset train
python scripts/videoattentiontarget_get_objects.py --dataset_path /path/to/videoattentiontarget --subset test
```
Could you please provide a dataset of your training at that time?

**Comment by francescotonini** [comment]
Hi, the dataset is GazeFollow _extended_, available [here](https://www.dropbox.com/s/3ejt9pm57ht2ed4/gazefollow_extended.zip?dl=0). Regarding the script not running, please send me the full script output so I can provide appropriate feedback. Thanks.

**Comment by Ki-Zhang** [comment]
Thank you for the dataset link. 
I downloaded the [dataset](https://www.dropbox.com/s/3ejt9pm57ht2ed4/gazefollow_extended.zip?dl=0) and ran the code:`python src/train.py experiment=gotd_gazefollow_pretrain_od`, which shows the following errors:
```bash
Traceback (most recent call last):
  File "/home/ki-zhang/Papercode/object-aware-gaze-target-detection-main/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/ki-zhang/Papercode/object-aware-gaze-target-detection-main/src/train.py", line 110, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train
    self._run_sanity_check()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check
    val_loop.run()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ki-zhang/Papercode/object-aware-gaze-target-detection-main/src/datamodules/components/GazeFollowObjects.py", line 232, in __getitem__
    return self.__get_test_item__(index)
  File "/home/ki-zhang/Papercode/object-aware-gaze-target-detection-main/src/datamodules/components/GazeFollowObjects.py", line 518, in __get_test_item__
    depth = Image.open(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/PIL/Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ki-zhang/Papercode/object-aware-gaze-target-detection-main/data/gazefollow_extended/depth2/00000000/00000001.jpg'
```
It seems to me that I don't have the file in directory of 'data/gazefollow_extended/depth2/00000000'. And I read the [GazeFollowObjects.py](https://github.com/francescotonini/object-aware-gaze-target-detection/blob/main/src/datamodules/components/GazeFollowObjects.py), line 518:
```bash
# Load depth
depth = Image.open(
        os.path.join(
        self.data_dir,
        self.keys_gazefollow[index],
    )
    .replace("train", "depth")
    .replace("test2", "depth2")
)
```
In the code, `self.keys_gazefollow[index]` is `test2/00000000/00000000.jpg`, which is replaced by `depth2/00000000/00000001.jpg`. But in GazeFollow extended dataset, the files are organized like:
```bash
gazefollow_extended/
├──test2 
	├── 00000000
	        ├── 00000001.jpg
                ...
	├── 00000001
	...
├── train
├── test_annotations_release.txt
├── train_annotations_release.txt
└── README.md
```
Hence, I don't know how to get the depth of each image.
Additionally, I ran the code `python scripts/videoattentiontarget_get_aux_faces.py --dataset_dir data/videoat
tentiontarget/ --subset train`(My videoattentiontarget dataset is placed under `data/` folder) and I get the following errors:
```bash
Traceback (most recent call last):
  File "/home/ki-zhang/Papercode/object-aware-gaze-target-detection-main/scripts/videoattentiontarget_get_aux_faces.py", line 26, in <module>
    df = pd.read_csv(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/videoattentiontarget/train.csv'
```
the downloaded [videoattentiontarget dataset](https://www.dropbox.com/s/8ep3y1hd74wdjy5/videoattentiontarget.zip?dl=0) is extracted like:
```bash
videoattentiontarget/
├── annotations
	├── test
                ├── CBS This Morning
                        ├── 1738_1919
                                ├── s00.txt
                                ....
                        ...
                ├── Downtown Abby
                ...
	└── train
└── images
```
so the currently downloaded dataset's annotations are in the such s*.txt files, which are scattered in many folders.

**Comment by chenwenhe11** [comment]
@Ki-Zhang I also encountered this problem, have you solved it?

**Comment by francescotonini** [comment]
Dear @Ki-Zhang and @chenwenhe11, I apologize for not getting back to you sooner. I updated the preprocessing scripts and included a third one for depth extraction. Updated instructions are available in the README.

Please re-open this issue if you have any problems; thanks.

**Comment by Ki-Zhang** [comment]
Thank you for your answer. However, I'm currently running into another problem when I run the code `python src/train.pyexperiment=gotd_gazefollow_pretrain_od`. I can't find the path to the pretrained model. Therefore, I cannot run the code `python src/train.pyexperiment=gotd_gazefollow model.net_pretraining={URL/PATH TO GAZEFOLLOW OD PRETRAINING}` populated with the pretrained model path.

**Comment by Ki-Zhang** [comment]
Thank you for your answer. However, I'm currently running into another problem when I run the code `python src/train.pyexperiment=gotd_gazefollow_pretrain_od`. I can't find the path to the pretrained model. Therefore, I cannot run the code `python src/train.pyexperiment=gotd_gazefollow model.net_pretraining={URL/PATH TO GAZEFOLLOW OD PRETRAINING}` populated with the pretrained model path.

**Comment by chenwenhe11** [comment]
Hello, when I run the following code when processing data, I get an error. 
Run the code as follows: 
python scripts/videoattentiontarget_get_aux_faces.py --dataset_path /path/to/videoattentiontarget --subset train 
The error is reported as follows: 
target_get_aux_faces.py", line 24, in <module>
    df = pd.read_csv(
pandas.errors.ParserError: Too many columns specified: expected 7 and found 2

Have you encountered this problem and how did you solve it?
