### ISSUE TITLE
Loss loss_gaze_vector is nan

### ISSUE THREAD

**Issue by Ki-Zhang** [francescotonini/object-aware-gaze-target-detection#3]
Thank you for your answer #2. 
However, I'm currently running into another problem when I run the code `python src/train.pyexperiment=gotd_gazefollow_pretrain_od`. I can't find the path to the pretrained model. Therefore, I cannot run the code `python src/train.pyexperiment=gotd_gazefollow model.net_pretraining={URL/PATH TO GAZEFOLLOW OD PRETRAINING}` populated with the pretrained model path.
Additionally, when I downloaded the provided checkpoints [videoattentiontarget](https://mega.nz/file/EI50DSoT#30pTdNe3hBo69jOsIt-oS6q_U8CV9MQ86ZKYDtOO0_Y) and ran the code `python src/train.pyexperiment=gotd_gazefollow model.net_pretraining=gotd_videoattenttiontarget.pth`, I had encountered the following errors:
```
Traceback (most recent call last):
  File "/data/data3/ki-zhang/object-aware-gaze-target-detection-main/src/utils/utils.py", line 39, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/data/data3/ki-zhang/object-aware-gaze-target-detection-main/src/train.py", line 112, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1163, in _run_train
    self.fit_loop.run()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1305, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/torch/optim/adamw.py", line 120, in step
    loss = closure()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 107, in _wrap_closure
    closure_result = closure()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 147, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 133, in closure
    step_output = self._step_fn()
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 406, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ki-zhang/miniconda3/envs/oagtd/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/data/data3/ki-zhang/object-aware-gaze-target-detection-main/src/models/gotd_module.py", line 123, in training_step
    raise ValueError(f"Loss {loss_name} is nan")
ValueError: Loss loss_gaze_vector is nan
```
I don't know how to fix it, and I hope I could get your help. Waiting for your reply.

**Comment by zmikd** [comment]
@Ki-Zhang I also encountered the same problem, have you solved it?

**Comment by francescotonini** [comment]
Hi both,

> I can't find the path to the pretrained model.

The checkpoints and artifacts are stored in the `logs/train/runs/{YYYY-MM-DD_hh-mm-ss}` directory, with each run generating its own dedicated folder.

> I had encountered the following errors:

I'm unable to reproduce these errors on my system; could you please share details about your configuration, such as the number of GPUs, GPU memory, etc.? Thanks.
